### PR TITLE
Install lizmap-plugin with plugin manager

### LINKED ISSUE #22: Use the new environment variable for LWC 3.5
Since LWC 3.5.1-pre, we need a new environment variable for QGIS Server to enable the plugins versions in the administration panel, and add the API entrypoint for the pyqgisserver.
CF https://docs.lizmap.com/current/en/install/pre_requirements.html#lizmap-server-plugin

### LINKED ISSUE #26: Use qgis-lizmap-server-plugin instead of Lizmap plugin

### PR DESCRIPTION
**Pull request by dmarteau**
## Install and configure the lizmap server plugin.

* Configuration: Install lizmap server plugin from the embedded `qgis-plugin-manager` in the qgis server image
* Set the `lizmapPluginAPIURL` in the drop-in configuration
* Add the variable `QGIS_SERVER_LIZMAP_REVEAL_SETTINGS` in the docker compose file.
* Change qgis server command to use a py-qgis-server configuration file for enabling the lizmap api.

* Ticket : fix #26, fix #22

### CODE REVIEW

**Review by Gustry — APPROVED** [review]
Thanks !

**Comment by nboisteault** [comment]
I have these errors :

Running as nboisteault

```bash
nboisteault@liz:~/3liz/infra/lizmap-docker-compose(lizmap-plugin-install)$ make configure
Configuring environment
Copying files
Creating directories
Creating env file
Installing lizmap plugin
QGIS server version : 3.22.7
Init https://plugins.qgis.org
Traceback (most recent call last):
  File "/usr/local/bin/qgis-plugin-manager", line 8, in <module>
    sys.exit(main())
  File "/opt/local/pyqgisserver/lib/python3.9/site-packages/qgis_plugin_manager/__main__.py", line 88, in main
    plugins.init()
  File "/opt/local/pyqgisserver/lib/python3.9/site-packages/qgis_plugin_manager/local_directory.py", line 56, in init
    with open(source_file, 'w', encoding='utf8') as f:
PermissionError: [Errno 13] Permission denied: 'sources.list'
Traceback (most recent call last):
  File "/usr/local/bin/qgis-plugin-manager", line 8, in <module>
    sys.exit(main())
  File "/opt/local/pyqgisserver/lib/python3.9/site-packages/qgis_plugin_manager/__main__.py", line 78, in main
    remote.update()
  File "/opt/local/pyqgisserver/lib/python3.9/site-packages/qgis_plugin_manager/remote.py", line 95, in update
    cache.mkdir()
  File "/usr/lib/python3.9/pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '.cache_qgis_plugin_manager'
Traceback (most recent call last):
  File "/usr/local/bin/qgis-plugin-manager", line 8, in <module>
    sys.exit(main())
  File "/opt/local/pyqgisserver/lib/python3.9/site-packages/qgis_plugin_manager/__main__.py", line 120, in main
    result = remote.install(*parameter)
  File "/opt/local/pyqgisserver/lib/python3.9/site-packages/qgis_plugin_manager/remote.py", line 248, in install
    xml_version = self.latest(plugin_name)
  File "/opt/local/pyqgisserver/lib/python3.9/site-packages/qgis_plugin_manager/remote.py", line 150, in latest
    return self.available_plugins().get(plugin_name)
  File "/opt/local/pyqgisserver/lib/python3.9/site-packages/qgis_plugin_manager/remote.py", line 144, in available_plugins
    for xml_file in self.xml_in_folder():
  File "/opt/local/pyqgisserver/lib/python3.9/site-packages/qgis_plugin_manager/remote.py", line 124, in xml_in_folder
    cache.mkdir()
  File "/usr/lib/python3.9/pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '.cache_qgis_plugin_manager'
make: *** [Makefile:17 : configure] Erreur 1

```

Running as root :

```bash
nboisteault@liz:~/3liz/infra/lizmap-docker-compose(lizmap-plugin-install)$ sudo make configure
Configuring environment
Copying files
Creating directories
./entrypoint.sh: ligne 37: su-exec : commande introuvable
make: *** [Makefile:17 : configure] Erreur 127

```

**Comment by dmarteau** [comment]
> PermissionError: [Errno 13] Permission denied: 'sources.list'

These file were existing and have the wrong permissions: it seems the were previously created as root: remove them or change their owner/group.

Plz, **do not run command as root**. This create directories with root permission and prevent services to use them as they do not run as root.

> ./entrypoint.sh: ligne 37: su-exec : commande introuvable

The command su-exec was intended to be run with  porter's build. It is executed only if your run as  root (you shouldn't)

**Comment by Gustry** [comment]
Going to try as well on my local

In `Dockerfile.installer`, this line can be removed `LIZMAP_PLUGIN_VERSION=3.7.4`

**Comment by dmarteau** [comment]
> In Dockerfile.installer, this line can be removed LIZMAP_PLUGIN_VERSION=3.7.4

Nevermind, this is for Porter installation and is going to be removed as unmaintained.

**Comment by Gustry** [comment]
Indeed I have the same issue : 

```
etienne@latitude ~/dev/lizmap/lizmap-docker-compose (lizmap-plugin-install) $ git reset --hard
HEAD is now at 7a31644 Install lizmap-plugin with plugin manager
etienne@latitude ~/dev/lizmap/lizmap-docker-compose (lizmap-plugin-install) $ git clean -df
etienne@latitude ~/dev/lizmap/lizmap-docker-compose (lizmap-plugin-install) $ make configure
```

**Comment by dmarteau** [comment]
What is your platform ?

**Comment by dmarteau** [comment]
Ok, I got it: wrong version of qgis-plugin-manager in the qgis image:  this work only with the **latest** verson of qgis-plugin-manager and it is embedded only in the **latest** build of 3liz/qgis-map-server:3.22, 3liz/qgis-map-server:3.24.  

----> Update your 3liz/qgis-map-server:*  images.

**Review by Gustry — APPROVED** [review]
The table is working in the administration panel, LGTM

**Review by nboisteault — APPROVED** [review]

**Pull request merged**
