### PR TITLE
Remove unmaintained Porter build

### PR DESCRIPTION
**Pull request by dmarteau**
### Remove porter because it unmaintained.
* A new branch `porter-branch` has been created and porter support moved to it.
* Rename `entrypoint.sh` to `configure.sh`

### CODE REVIEW

**Review by Gustry — COMMENTED** [review]
I was not using Porter and I didn't know that, so I will let you this PR

**Comment by dmarteau** [comment]
To be clear, this not Porter which is unmainained but the build for lizmap-docker-compose into a CNAB container.

**Review by nboisteault — APPROVED** [review]
Could you replace `docker-compose` by `docker compose` too?

**Comment by dmarteau** [comment]
> Could you replace docker-compose by docker compose too?

Replaced occurences of command   `docker-compose` to `docker compose`.

**Review by nboisteault — APPROVED** [review]
LGTM

**Comment by Gustry** [comment]
Thanks @dmarteau 
I'm removing the branch because you are on the 3liz repository

**Pull request merged**
